---

- name: Cisco ios config examples
  gather_facts: False
  hosts: routers
  connection: ansible.netcommon.network_cli

  tasks:
    
     - name: Interface Configuration
       cisco.ios.ios_interfaces:
          config:
             - name: GigabitEthernet3
               description: Changed by Guy
               enabled: true
               speed : 1000
               mtu: 9000
              
          state: merged

       register: int
     - debug: 
          var: int.before
     - debug:
          var: int.commands
     - debug:
          var: int.after
