---
- name: IOS Static Route Demo
  hosts: routers
  tasks:
    ################### IP Config Merged ##############
    - name: Config Static Route1
      ios_static_route:
        prefix: 10.1.1.0
        mask: 255.255.255.0
        next_hop: 192.168.0.1
        state: present
      register: route1
    - debug:
        var: route1.commands
